apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-worker
  namespace: fitai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-worker
  template:
    metadata:
      labels:
        app: auth-worker
    spec:
      containers:
        - name: auth-worker
          image: backend-auth-service:latest
          imagePullPolicy: IfNotPresent
          command: ["celery", "-A", "auth_service", "worker", "-l", "info"]
          envFrom:
            - configMapRef:
                name: fitai-env
          resources:
            requests:
              memory: "300Mi"
              cpu: "150m"
            limits:
              memory: "600Mi"
              cpu: "300m"
