apiVersion: v1
kind: ConfigMap
metadata:
  name: fitai-env
  namespace: fitai
data:
  # Redis
  REDIS_HOST: redis
  REDIS_PORT: "6379"

  # RabbitMQ
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"

  # Django
  DJANGO_DEBUG: "1"
